---
- name: "add yum repositories"
  yum: name={{item}}
  with_items:
    - http://ftp-srv2.kddilabs.jp/Linux/distributions/fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm
    - http://rpms.famillecollet.com/enterprise/remi-release-6.rpm

- name: "replace enable paramater in repository config files"
  replace: dest=/etc/yum.repos.d/{{item}} regexp="enabled *= *1" replace="enabled=0"
  with_items:
  - epel.repo
  - remi.repo

- name: "install php"
  yum: name=php state=latest enablerepo=remi-php55

