---
- name: "add yum repositories"
  yum: name={{item}}
  with_items:
  - http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm

- name: "replace enable paramater in repository config files"
  replace: dest=/etc/yum.repos.d/{{item}} regexp="enabled *= *1" replace="enabled=0"
  with_items:
  - mysql-community.repo

- name: "install mysql"
  yum: name={{item}} state=latest enablerepo=mysql56-community
  with_items:
  - mysql
  - mysql-server
  notify:
  - restart_mysqld

